### ISSUE TITLE
Rake conflict upgrading from application_ruby cookbook from 3.x to 4.x

### ISSUE THREAD

**Issue by SimonKaluza** [poise/application_ruby#87]
We've been trying to move our deployment cookbooks over to the application_ruby 4.x and application 5.x releases, but it seems having the application_ruby cookbook manage our Ruby version has caused the new way of calling the Rake gem to get a bit confused.

We previously managed our own Ruby versions using the rbenv cookbook.  Now when we run the deployment chef-client fails because it cannot find the Rake script/executable (binstub?).  Manually installing the Rake Gem with:
```
  ruby_gem 'rake' do
    options '--force'
  end
```

did not help either.

Here is the output in both cases:

```
application_rails[myapp] action deploy
    * file[/path/to/myapp/config/database.yml] action create (up to date)
    * ruby_execute[rake assets:precompile] action run
      
      ================================================================================
      Error executing action `run` on resource 'ruby_execute[rake assets:precompile]'
      ================================================================================
      
      Mixlib::ShellOut::ShellCommandFailed
      ------------------------------------
      Expected process to exit with [0], but received '1'
      ---- Begin output of ["/usr/local/rbenv/shims/ruby", "rake", "assets:precompile"] ----
      STDOUT: 
      STDERR: ruby: No such file or directory -- rake (LoadError)
      ---- End output of ["/usr/local/rbenv/shims/ruby", "rake", "assets:precompile"] ----
      Ran ["/usr/local/rbenv/shims/ruby", "rake", "assets:precompile"] returned 1
      
      Cookbook Trace:
      ---------------
      /var/chef/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:69:in `notifying_block'
      /var/chef/cache/cookbooks/application_ruby/files/halite_gem/poise_application_ruby/resources/rails.rb:175:in `action_deploy'
      
      Resource Declaration:
      ---------------------
      # In /var/chef/cache/cookbooks/application_ruby/files/halite_gem/poise_application_ruby/resources/rails.rb
      
      231:           ruby_execute 'rake assets:precompile' do
      232:             command %w{rake assets:precompile}
      233:             user new_resource.parent.owner
      234:             group new_resource.parent.group
      235:             cwd new_resource.parent.path
      236:             environment new_resource.app_state_environment
      237:             ruby_from_parent new_resource
      238:             parent_bundle new_resource.parent_bundle if new_resource.parent_bundle
      239:           end
      240:         end
```

**Comment by SimonKaluza** [comment]
Removing rbenv entirely from our server and PATH then using this cookbook to manually manage its own ruby versions fixed the rake conflict.
